version: "3.7"
services:
    nginx:
        image: nginx
        restart: always
        ports:
            - 19901:80
        depends_on: 
            - proxy
        volumes:
            - ./src/dist:/usr/share/nginx/html
            - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    proxy:
        build: proxy
        restart: always
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        depends_on: 
            - mysql
        volumes:
            - ./proxy/index.js:/usr/share/app/index.js
        entrypoint: ['npm', 'run', 'start']
    
    mysql:
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: apteka
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - './proxy/schema.sql:/docker-entrypoint-initdb.d/setup.sql'

    builder:
        build: src
        restart: always
        environment:
          - ENV=DEV
        volumes:
            - ./src/src:/usr/share/app/src
            - ./src/dist:/usr/share/app/dist
        entrypoint: ['npm', 'run', 'watch']